# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

#trigger: one
trigger:
  branches:
    include:
    - dev
pool:
  vmImage: ubuntu-latest

steps:
#- task: TerraformInstaller@1
#  displayName: "Terraform Install"
#  inputs:
#    terraformVersion: 'latest'
#- task: TerraformTaskV4@4
#  displayName: "Terraform Init"
#  inputs:
#    provider: 'azurerm'
#    command: 'init'
#    backendServiceArm: 'TF-MGMT-SUB'
#    backendAzureRmResourceGroupName: 'TEST-DEPLOYMENTS-TF-STATE'
#    backendAzureRmStorageAccountName: 'terraformstate12375'
#    backendAzureRmContainerName: 'terraformstate'
#    backendAzureRmKey: 'terraform.tfstate'

- task: MicrosoftSecurityDevOps@1
  displayName: 'Microsoft Security DevOps'